import { Layouts } from "react-grid-layout";

//TODO:modify md  sm xs

export const layouts: Record<string, Layouts> = {
  all: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 1, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 1 },
      { i: "animatedEmoji", x: 2, y: 0, w: 2, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 2, h: 1 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 1 },
      { i: "webAgent", x: 0, y: 0, w: 2, h: 2 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
  },

  about: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 1 },
      { i: "animatedEmoji", x: 2, y: 0, w: 2, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 2, h: 1 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 1 },
      { i: "webAgent", x: 0, y: 0, w: 2, h: 2 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
  },

  projects: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 1 },
      { i: "animatedEmoji", x: 2, y: 0, w: 2, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 2, h: 1 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 1 },
      { i: "webAgent", x: 0, y: 0, w: 2, h: 2 },
      { i: "actions", x: 0, y: 2, w: 2, h: 2 },
      { i: "paper", x: 3, y:2 , w: 2, h: 2 },
    ],
  },
};

export const selectedCard: Record<string, Record<string, boolean>> = {
  all: {
    avatar: true,
    themeSwitch: true,
    animatedEmoji: true,
    mapComponent: true,
    iconCloud: true,
    webAgent: true,
    actions: true,
    paper: true,
  },
  about: {
    avatar: true,
    themeSwitch: false,
    animatedEmoji: false,
    mapComponent: true,
    iconCloud: true,
    webAgent: false,
    actions: false,
    paper: false,
  },
  projects: {
    avatar: false,
    themeSwitch: false,
    animatedEmoji: true,
    mapComponent: false,
    iconCloud: false,
    webAgent: true,
    actions: true,
    paper: true,
  },
};